server:
  port: 10426

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: gaofan.1994
    url: jdbc:mysql://localhost:3306/api?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  thymeleaf:
    # ������ͼ·��ǰ׺
    prefix: classpath:/templates/
    # ������ͼ·����׺
    suffix: .html
    mode: html
    # �رջ��� �޸���ͼ ˢ�����������ʾ �����׶���عرջ��� (=false)
    cache: false
